<Project>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>2.0.1</Version>
    <Authors>Yiming</Authors>
    <Product>Infinite_Ammo</Product>
    <Deterministic>true</Deterministic>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <ExiledReferencesDir Condition="'$(ExiledReferencesDir)' == ''">$(MSBuildThisFileDirectory)..\packages\ExMod.Exiled.9.5.0\lib\net48</ExiledReferencesDir>
    <ExiledGameManagedDir Condition="'$(ExiledGameManagedDir)' == ''">$(MSBuildThisFileDirectory)..\Server_NapCha_ui_API\bin\Debug</ExiledGameManagedDir>
    <LabApiGameManagedDir Condition="'$(LabApiGameManagedDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed</LabApiGameManagedDir>
  </PropertyGroup>
</Project>
